[package]
name = "btdt"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
nanoid = "0.4.0"
rand = { version = "0.8.5", features = ["std_rng"] }
rkyv = { version = "0.7.45", features = ["validation"] }

[dev-dependencies]
tempfile = "3.15.0"
