[workspace]

[[package]]
name = "btdt"
changelog_update = false
git_release_enable = false
version_group = "btdt"

[[package]]
name = "btdt-cli"
changelog_include = ["btdt"]
changelog_path = "CHANGELOG.md"
git_release_name = "v{{ version }}"
version_group = "btdt"

[[package]]
name = "btdt-server"
changelog_include = ["btdt"]
changelog_path = "CHANGELOG.md"
git_release_name = "v{{ version }}"
version_group = "btdt"
