name: Build and deploy documentation

on:
  push:
    branches: ["main"]
    
env:
    MDBOOK_VERSION: 0.4.45
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Install mdbook
        run: |
          curl --location https://github.com/rust-lang/mdBook/releases/download/v${{ env.MDBOOK_VERSION }}/mdbook-v${{ env.MDBOOK_VERSION }}-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xz --directory /usr/local/bin
        
      - name: Build
        run: mdbook build
        working-directory: doc

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/book
